### PR TITLE
Add more test scenarious for Compiler Factory and Pom editor

### PR DESCRIPTION
**Pull request by jakubschwan**

### CODE REVIEW

**Comment by desmax74** [comment]
@jakubschwan where is the org.kie.workbench.common.services.backend.compiler.ResourcesConstants ?

**Comment by jakubschwan** [comment]
oh I didn't added into commit, good catch

**Comment by jakubschwan** [comment]
@desmax74 ResourcesConstants added
Now it contains only one Path, but I'll add more in next PRs

**Comment by desmax74** [comment]
@jakubschwan  The lack of @Test in the new methods of KieMavenCompilerFactoryTest is intentional to disable temporarly ?

**Pull request merged**
